[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Exclude sitemaps and static files from SPA redirect
[[redirects]]
  from = "/sitemap-*.xml"
  to = "/sitemap-:splat.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# Cart page redirects for SEO
[[redirects]]
  from = "/2-passenger-golf-cart"
  to = "/2-passenger-golf-cart-rental-ocala"
  status = 301

[[redirects]]
  from = "/2-passenger-deluxe-golf-cart"
  to = "/2-passenger-deluxe-golf-cart-rental-ocala"
  status = 301

[[redirects]]
  from = "/4-passenger-golf-cart"
  to = "/4-passenger-golf-cart-rental-ocala"
  status = 301

[[redirects]]
  from = "/4-passenger-deluxe-golf-cart"
  to = "/4-passenger-deluxe-golf-cart-rental-ocala"
  status = 301

[[redirects]]
  from = "/6-passenger-golf-cart"
  to = "/6-passenger-golf-cart-rental-ocala"
  status = 301

[[redirects]]
  from = "/lifted-4-passenger-golf-cart"
  to = "/lifted-4-passenger-golf-cart-rental-ocala"
  status = 301

[[redirects]]
  from = "/utility-golf-cart-rental"
  to = "/utility-golf-cart-rental-ocala"
  status = 301

[[redirects]]
  from = "/daily-rental"
  to = "/3-day-rental"
  status = 301

# SPA fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
